spring.application.name=ProyectoSpringAvanzado

#configuracion de la base de datos mysql

spring.datasource.url=jdbc:mysql://localhost:3306/personadb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ibarra


#driver para la base de datos mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#Config para JPA y Hibernate

#Sirve para actualizar la base de datos del entity
spring.jpa.hibernate.ddl-auto=update  
#Muestra las consultas en la consola
spring.jpa.show-sql=true
#Optimiza sql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect




